server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
#            - After=2020-09-23T17:41:53.993+08:00[Asia/Shanghai]
#            - Before=2020-09-23T18:41:53.993+08:00[Asia/Shanghai]
            - Between=2020-09-23T17:41:53.993+08:00[Asia/Shanghai],2020-09-25T10:05:53.993+08:00[Asia/Shanghai]
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/